### ISSUE TITLE
Support search by movie title with article at the end - eg "Empire Strikes Back, The"

### ISSUE THREAD

**Issue by rmrector** [xbmc/metadata.themoviedb.org.python#11]
As described here... [2888898](https://forum.kodi.tv/showthread.php?pid=2888898#pid2888898)

It seems both the XML scraper and this Python scraper are being tripped up when the word "The" is positioned at the end of the title. eg **Empire Strikes Back, The**

No results are found until the word "The" is removed from the title.

[From the forums](https://forum.kodi.tv/showthread.php?tid=344580&pid=2895171#pid2895171)

**Comment by rmrector** [comment]
[A thread on TMDB](https://www.themoviedb.org/talk/5d6e0b0265686e3899882a75) about this change.

**Comment by KarellenX** [comment]
Right. Thanks for the link. I'll let the member that raised the issue know

**Comment by rmrector** [comment]
closed by #15
