### ISSUE TITLE
The rating name should be changed from "tmdb" to "themoviedb"

### ISSUE THREAD

**Issue by rmrector** [xbmc/metadata.themoviedb.org.python#12]
Ratings for TheMovieDB are scraped as follows using Universal Movie scraper and TheMovieDB XML scraper
```xml
<rating name="themoviedb" max="10">
    <value>7.700000</value>
    <votes>12873</votes>
</rating>
```

This Python scraper saves the rating as
```xml
<rating name="tmdb" max="10">
            <value>5.200000</value>
            <votes>5200</votes>
        </rating>
```
The rating name should be changed from "tmdb" to "themoviedb"

[From the forums](https://forum.kodi.tv/showthread.php?tid=344580&pid=2899128#pid2899128)

**Comment by Razzeee** [comment]
really confusing, that it's using `tmdb` for the unique id, but `themoviedb` for this.

@KarellenX can you say what exactly this breaks?

**Comment by KarellenX** [comment]
The only reason I raised it was to keep consistency in users libraries.

The current XML scrapers- Universal Movie Scraper and TheMovieDB XML scraper both use "themoviedb" as the rating identifier for movies. But this python scraper is using "TMDB"

I don't think this breaks anything, or anything of any consequence. There may be skins searching for "themoviedb" and not "tmdb" to display the rating icon as an example.

**Comment by rmrector** [comment]
Ya, as Karellen said no major _breakage_. Skins and JSON-RPC consumers may look for specific values, but they should be designed to handle a missing value gracefully.

If we want to keep "tmdb" we should consider changing the XML scrapers. Consistency with existing NFO files and media managers may also need to be considered.

**Comment by rmrector** [comment]
My short-term plan is to merge this change to match existing scrapers, and later the discussion to change it to "tmdb" to match uniqueids can be in the context of all scrapers.

**Comment by Razzeee** [comment]
That's fine, I did not mean to hold this up
