### ISSUE TITLE
Fanart language seems to be ignored

### ISSUE THREAD

**Issue by mkaflowski** [xbmc/metadata.themoviedb.org.python#123]
I have set "pl" langague but I enabled fanart and set "en". For movies like "Meet the Fockers" I get "pl" poster. Why?
Does it should be?:
"en" (fanart) -> "pl" (tmdb)
and for "pl" set in fanart:
"pl" (fanart) -> "en" (fanart as fallback in the new version) -> "pl" (tmdb)

**Comment by KarellenX** [comment]
So you want Polish language metadata, but you want all artwork to be English. Is that correct?

Could you explain where you changed the setting. thanks.

**Comment by mkaflowski** [comment]
I want to prioritize fanart. Polish posteres from tmdb are bad quality very often. In the previous version when I set "en" in fanart settings an english fanart was set.

**Comment by KarellenX** [comment]
Ok, but you still haven't answered my second question.

**Comment by mkaflowski** [comment]
What do you mean by accessing screen? 
![image](https://user-images.githubusercontent.com/10148175/148664688-36de43af-7bd2-420f-a3a7-47eb7a620055.png)
![image](https://user-images.githubusercontent.com/10148175/148664691-db6466c5-c407-4b43-b118-59bcf6e494aa.png)

**Comment by KarellenX** [comment]
Thanks, but how did you get to that screen?

Did you go Settings>Addons>My Addons> Information Provider>Movies

or did you go to Videos>Files>Your Source>Change Content?

Which one?

**Comment by mkaflowski** [comment]
Videos>Files>Your Source>Change Content

**Comment by mkaflowski** [comment]
Ok, I see that posters are sorted by language in `combine_scraped_details_available_artwork`. I will try to add an option to have ability to prioritize fanart.

**Comment by KarellenX** [comment]
>Videos>Files>Your Source>Change Content

Great. And bad. 
Bad because I was hoping you used the other method, which would explain the problem.

Great because you obviously know the difference between the two. The other one sets a default, and has no effect on existing Sources.

>Ok, I see that posters are sorted by language in combine_scraped_details_available_artwork. I will try to add an option to have ability to prioritize fanart.

As soon as I get home I will test it to check if I have the same results. I am sure I will.

**Comment by mkaflowski** [comment]
Ok something like this should be good:
```python
def combine_scraped_details_available_artwork(original_details, additional_details, language):
    if language:
        # Image languages don't have regional variants
        language = language.split('-')[0]
    if additional_details and additional_details.get('available_art'):
        available_art = additional_details['available_art']
        if not original_details.get('available_art'):
            original_details['available_art'] = {}
        for arttype, artlist in available_art.items():
            artlist = sorted(artlist, key=lambda x:x['lang']==language, reverse=True)
            combinlist = artlist + original_details['available_art'].get(arttype, [])
            original_details['available_art'][arttype] = combinlist

            # option for [if fanart is not priritized]
            original_details['available_art'][arttype] = sorted(combinlist, key=lambda x:x['lang']==language, reverse=True)

    return original_details
```

When I change python files do I have to restart Kodi every time to see results (I use macos)?
