### ISSUE TITLE
Set Information not scraped

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#150]
Just noticed today that when I scraped Doctor Strange in the Multiverse of Madness (2022) into my library, no Set data was scraped.

The two movies are part of a Set... https://www.themoviedb.org/collection/618529-doctor-strange-collection
The API response provides Set data... [API](https://api.themoviedb.org/3/movie/453395?api_key=f090bb54758cabf231fb605d3e3e0468&language=en-US&append_to_response=trailers%2Cimages%2Creleases%2Ccasts%2Ckeywords)

But no Set data is added to the library, or visible in the exported NFO file.
Also no Set artwork is downloaded either from fanart.tv or TMDB. 

Log... https://paste.kodi.tv/iwiweterub.kodi

I then tried scraping Spider-Man No Way Home (2021) and no Set data was scraped there either.

**Comment by rmrector** [comment]
The API isn't returning a collection name. Kodi won't create a set without a name.

**Comment by KarellenX** [comment]
@rmrector 

https://www.themoviedb.org/talk/62b816dc229ae20b5c7ed7ca

https://www.themoviedb.org/talk/62b7593bf0317400616a9f34

**Comment by KarellenX** [comment]
All fixed at TMDB and movie sets are scraping correctly again.

I'll close this report.
