### ISSUE TITLE
Request to handle TMDB ID´s in file names

### ISSUE THREAD

**Issue by Spoon3er** [xbmc/metadata.themoviedb.org.python#179]
It would be great to be able to parse the TMDB ID in the file name. As it is for now the search function is tmdb/12345, which you cant name a file with, because of the "/".

As it is only one line of code i made a pull request. Don´t know if this will be an issue somewhere else, but for me it is working.

**Comment by Spoon3er** [comment]
#180

**Comment by rmrector** [comment]
implemented in #205
