### ISSUE TITLE
Missing Documentation?

### ISSUE THREAD

**Issue by LukeV1** [xbmc/metadata.themoviedb.org.python#187]
Hi all,

I am using this addon in KODI - and I'm a big fan of it!
Unfortunately some of my movies and series stayed undetected. Since not being an absoulte beginner to programming I decided to take a look at the code to figure out why it doesn't like them.

But I'm somehow stuck understanding the codebase because I can not find any documentation on the addon or code itself. Is there really nothing documented?

I am particularly interested in how the (movie) source Paths are searched through and how it parses film names from these folders to search for it on tMDB.

Best regards
Luke

**Comment by KarellenX** [comment]
There is no documentation.

If you provide a debuglog that captures the scraping of the problem movies, I can check what the problem is.

**Comment by KarellenX** [comment]
No response. Issue closed.
