### ISSUE TITLE
Folder name not used for search?

### ISSUE THREAD

**Issue by LukeV1** [xbmc/metadata.themoviedb.org.python#194]
Hello again..

I found another kind of issue in the log files that I don't really understand.

- If a folder contains a dvd image (*.ifo files, etc.), the scraper automatically takes the folder name to search for the movie.
- If a folder contains a packed dvd image (*.iso file), the scraper takes only the file name of the iso file for the seach. If this fails, it is not performing a search using the folder name but skips the movie entirely.

It seems to me that the scaper is making things a bit too easy for himself ;)

I added an examle here: [log.txt](https://github.com/xbmc/metadata.themoviedb.org.python/files/11242428/log.txt)
The file structure is here:
![grafik](https://user-images.githubusercontent.com/8466561/232315934-824c0b6e-5521-4779-bdf7-5eafcf425f34.png)

When searching the folder name "Die Tribute von Panem (2) - Catching fire" TMDB succeeds. But when searching only the file name "tribute catching fire disc1" it fails. 

---

I think this problem applies to many other cases as well, i.e. when the file in the folder is just named "Disc1.iso" or something...

**Comment by KarellenX** [comment]
@LukeV1 

Your folder name is...
`smb://ZOTAC/FILME/eigene-Filme/Die Tribute von Panem (2) - Catching fire/`

But the search string is **TRIBUTE CATCHING FIRE DISC1** 

Two problems...
1. The folder name is correct but the file naming is wrong as there is no such movie as TRIBUTE CATCHING FIRE DISC1.
2. You most likely have not enabled the setting _Movies are in separate folders that match the movie title_ in the Source settings, which forces the use of the folder name for the search string.

**Comment by LukeV1** [comment]
I have checked it.
_Movies are in separate folders that match the movie title_ was not enabled. And you were right, this solved quite a lot of issues I encountered. 
**Thanks for that hint!**

Still, I think it would be nice if the parser tried the movie file's parent folder name if nothing was found to search again for it. But this is now definitely a feature request and not a bug.

**Comment by LukeV1** [comment]
> Can't. Not everybody uses movie folders. Some just add the video file directly into the Source, so there are hundreds or thousands of movies in a single folder.

Ah! Thats right. So it has to be the way it is.

My new problem is how MakeMKV saves movies. Take this example:
![grafik](https://user-images.githubusercontent.com/8466561/233611346-70e73975-8a9c-4e7a-80a5-a294d82766d1.png)

Besides the main movie some - sometimes many - additional files are stored (with trailers, outtakes, extras,... - all the other stuff accessible from the movie's main menu). Now I get an entry for each file in that folder, all of which are recognized as the movie. My Kodi library is now crammed with several hundred duplicate entries containing all the extras, trailers,... Some movies now appear 20 times in the library view.
Quite a mess.

**Comment by KarellenX** [comment]
https://kodi.wiki/view/Add-on:Extras

**Comment by LukeV1** [comment]
Oh dear. I was too stupid.
This is exactly the gold mine I've been looking for.

I'm sorry for having bothered you with all these stupid questions..

Thanks again!
