### ISSUE TITLE
Running continuosly

### ISSUE THREAD

**Issue by MrHappy** [xbmc/metadata.themoviedb.org.python#213]
I did a clean install of libreelec (on a rpi) and this plugin keeps running continuously.
How can I find out why it keeps running in a loop?
This seems to prevent libreelec from cleaning the database (and therefor flooding the logfile with a lot of errors of files it cannot find).

**Comment by KarellenX** [comment]
Need a debuglog that captures the problem.
And you should have asked this question on the forum. Please do so.
