### ISSUE TITLE
Scraper not available in v19 Matrix

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#33]
After a recent update to a more recent v19 nightly, the version of this scraper installed via zip is no longer compatible and disabled.

The scraper is not available in the v19 repository.

Please make this scraper available for v19.

**Comment by mrobe** [comment]
+1

I'd love to try this in v19 too.

**Comment by rmrector** [comment]
For the next version I'll tinker with RomanVM's script to automatically submit to both repositories.

**Comment by mrobe** [comment]
Any status on this issue?

**Comment by rmrector** [comment]
The latest version, 1.2.0, is available in the official repo for both Kodi 18 and Kodi 19.

**Comment by KarellenX** [comment]
Thanks :)
