### ISSUE TITLE
Problem with pt-br language

### ISSUE THREAD

**Issue by k2-br** [xbmc/metadata.themoviedb.org.python#44]
The setings.xml file describes the Brazilian Portuguese language as pt-br, however the correct one is pt-BR. The lowercase string is returning the same results as (pt) portuguese of portugal.

Please change from pt-br to pt-BR.

**Comment by rmrector** [comment]
Thanks, I'll take a look. Can you list the names of a few movies affected?

**Comment by k2-br** [comment]
Yes.
The movie "Terminator: Dark Fate"
with pt or pt-br: "Exterminador Implacável: Destino Sombrio"
com pt-BR: "O Exterminador do Futuro: Destino Sombrio"

URL Example:
with pt:
http://api.themoviedb.org/3/discover/movie?api_key=YOUKEY&with_genres=28&page=1&language=pt

with pt-br:
http://api.themoviedb.org/3/discover/movie?api_key=YOUKEY&with_genres=28&page=1&language=pt-br

with pt-BR
http://api.themoviedb.org/3/discover/movie?api_key=YOUKEY&with_genres=28&page=1&language=pt-BR


In the url examples, you will notice that the results in pt and pt-br are the same. Therefore, the need to capitalize the BR.

Several films and series have different titles for Brazil and Portugal
