### ISSUE TITLE
Set as default movie scraper

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#51]
@rmrector 

Could your scraper please be set as the default movie scraper for v19. 

I have used it for well over a year now and it is robust and works extremely well. 

The current XML scrapers have many bugs and are essentially unmaintained. We should be offering users the best we have.

(The Music library has already switched over to the Python version of scrapers as default.)

**Comment by rmrector** [comment]
Addressed with [xbmc#18619](https://github.com/xbmc/xbmc/pull/18619), it is now the default scraper in Kodi 19 nightlies and should be in alpha 3.
