### ISSUE TITLE
Error Type: <type 'exceptions.AttributeError'>

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#53]
Using the **tmdb/188412** method to scrape a movie, the scraper errors on some movies.

Log can be found here... https://paste.kodi.tv/ezonoqegob.kodi
A successful scrape can be found on line 1032
Failed scrape can be found on line 1497

The second item is designated as an Adult movie on TMDB.

Using a Parsing NFO file also fails,, whereas this would work with the XML version of the scraper.

The failed scrape results in a completely empty movie entry

![failed](https://user-images.githubusercontent.com/44626605/93005132-6c0bd800-f591-11ea-91e0-c2b619771af4.jpg)

**Comment by rmrector** [comment]
@KarellenX can you see if this still happens with 1.3.0?

**Comment by KarellenX** [comment]
Using v1.3.0+matrix1 I was able to scrape an adult title...

Using the **tmdb/188412** now works. Line 2209... https://paste.kodi.tv/fubowezonu.kodi

Using a Parsing NFO also worked when scraping an adult title.

The issue is fixed. Thanks :)

**Comment by rmrector** [comment]
Thanks for testing, I had a feeling PK's dependency change would clear that up.
