### ISSUE TITLE
Artwork Settings

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#56]
Now that new settings for artwork have been merged into v19 allowing a user to select None, Custom, Basic and Maximum artwork levels, is it necessary to keep artwork settings in scrapers also?

I note that the music scrapers by ronie have done away with artwork settings, instead relying on the new Kodi artwork settings to determine which artwork is used.

It would be more streamlined to have a single step to set artwork, rather than the two step system we have now of 1. Scrapers and 
2. advancedsettings.xml / the new artwork settings.

**Comment by KarellenX** [comment]
As these settings have no effect if the second step is not implemented, then why not leave these settings enabled by default and remove them from the settings page so they are not visible to the user.

A user then only needs to set the second step, and from their point of view it is only a single step to get artwork.

**Comment by rmrector** [comment]
Agreed.

**Comment by KarellenX** [comment]
Thanks @rmrector 

Your thoughts @pkscout ? Would you like me to post the same issue in your tv show repo also?

**Comment by pkscout** [comment]
Posting the issue to the TMDb tv show scraper is fine with me, but I need a link (or something) to information on the new settings and how to access them. I'm not familiar with those. I agree to simpler setup for sure though.
