### ISSUE TITLE
Selected language ignored for Posters

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#59]
A member has reported that scraping movies in German always returns an English poster. Two examples he provided are...

https://www.themoviedb.org/movie/12495-das-singende-klingende-b-umchen
https://www.themoviedb.org/movie/8703-t-i-o-ky-pro-popelku

I confirmed that when setting the scraper language to de-DE, the English poster is scraped, even though German posters exist.

In the API return, the primary poster with "en" language is listed first, then the language specific posters follow.
It seems the scraper picks the first poster out of the list, ignoring the language.
https://api.themoviedb.org/3/movie/12495?include_image_language=de%2Cen%2Cnull&api_key=f090bb54758cabf231fb605d3e3e0468&append_to_response=trailers%2Cimages%2Creleases%2Ccasts%2Ckeywords&language=de-DE

Scraping starts at line 1040... https://paste.kodi.tv/oveyatomax.kodi

**Comment by Mister-XY** [comment]
i see another small error. If the scraper did not found a german or english poster, he did not load any posters.
https://www.themoviedb.org/movie/28610-prinzessin-lillifee
https://www.themoviedb.org/movie/52611-el-rat-n-p-rez-2
https://www.themoviedb.org/movie/36617-p-rez-el-ratoncito-de-tus-sue-os
