### ISSUE TITLE
Posters not scraped in selected language

### ISSUE THREAD

**Issue by KarellenX** [xbmc/metadata.themoviedb.org.python#61]
The XML scraper has been experiencing issues for the last few weeks, and I have been recommending users to switch over to this Python scraper so they can continue scraping.

Unfortunately I have a steady stream of complaints that the users keep getting English posters instead of posters in their selected language.

Is there any chance this can be fixed? IIRC I think I raised this a couple of months ago.

If you need an example to test, 
https://www.themoviedb.org/movie/625568-unhinged/images/posters?image_language=fr

**Comment by rmrector** [comment]
That example works fine here, I end up with a French poster and details as expected when the scraper is configured with fr-FR. This was fixed with 1.3.1.

**Comment by KarellenX** [comment]
Thanks @rmrector 

Do you mind looking at this log... https://paste.kodi.tv/azayufaxoq.kodi

I have just done a fresh start and same thing happens...

Scrape starts at line 842
Line 961 is poster being cached, and I have realised the poster is coming from fanart.tv. Why is themoviedb being ignored as first choice, and instead scraping an English poster from fanart.tv?

https://fanart.tv/movie/625568/unhinged/

**Comment by rmrector** [comment]
FTV images are set first if available. You have FTV configured for English images.

**Comment by KarellenX** [comment]
Oh, bugger. I forgot there was a language setting for fanart.tv. Over the last couple of weeks I have been chopping and changing between six versions of scrapers.

Right, I was unaware that fanart.tv had priority.

thanks @rmrector I guess other users are forgetting to set language for images also.
