### ISSUE TITLE
[Request] Option to disable Season titles

### ISSUE THREAD

**Issue by mathu204** [xbmc/metadata.themoviedb.org.python#64]
I am using Titan Bingie Mod and i have some shows that use the Season titles rather than the numbers and by doing this it places the seasons out of order, if it was in the correct order it wouldnt be an issue for me but it is. Can you consider adding an option to just use regular season numbers rather than season titles when scraping and adding metadata for TV shows?

**Comment by KarellenX** [comment]
Please provide the link to a TV Show that scrapes seasons out of order

**Comment by mathu204** [comment]
> Please provide the link to a TV Show that scrapes seasons out of order

DBZ, Naruto Shippuden, Archer are examples I manually renamed the seasons to the numerical format on the tmdb website with my account for Naruto, and I think dbz Or I may have just switched to tvdb for that one, Archer should still be there. It doesn’t scrape out of order per say it’s just that when I go into season view using the Titan bingie mod skin (it may be something skin sided) the seasons are ordered alphabetically rather than release date

**Comment by KarellenX** [comment]
Well, can I have the links?

**Comment by mathu204** [comment]
https://www.themoviedb.org/tv/10283-archer/seasons
https://www.themoviedb.org/tv/31910-naruto-shipp-den/seasons
https://www.themoviedb.org/tv/12971/seasons

**Comment by KarellenX** [comment]
Ummm, you have given me TV Shows, but you have posted in the Movie Scraper repository.

Which scraper are you using? Provide the correct name and version number of the scraper and the version of Kodi you are using.

**Comment by mathu204** [comment]
> Ummm, you have given me TV Shows, but you have posted in the Movie Scraper repository.
> 
> Which scraper are you using? Provide the correct name and version number of the scraper and the version of Kodi you are using.

Sorry I am using TheMovieDB Scraper that does both TV and Movies this is the MovieDB Python. My mistake sorry for the inconvenience
