### ISSUE TITLE
Support for TV drama scraping

### ISSUE THREAD

**Issue by zhengfan2014** [xbmc/metadata.themoviedb.org.python#65]
I really like this python scraper, I hope I can use it to scrape TV shows😄

**Comment by KarellenX** [comment]
Yes you can. Install **TMDB TV Shows** from the Kodi repository

**Comment by zhengfan2014** [comment]
> Yes you can. Install **TMDB TV Shows** from the Kodi repository

I am not a kodi user, I am a plug-in developer, and I want to see an example of a TV scraper written in python
