### ISSUE TITLE
[Request] Option to lower images resolution

### ISSUE THREAD

**Issue by D4anielCB** [xbmc/metadata.themoviedb.org.python#71]
Hi there, I think that would be great if we had the option to lower the quality from the scrapped images, as there are a lot of tv boxes that has only 8gb internal storage as mibox. 
I believe that would be very simple to implement just change the /original/ in the url image of tmdb to /w500/ or other resolutions

Thanks in advance

**Comment by rmrector** [comment]
I'm not real excited about saving that smaller size into the library data by handling this in the scraper.

This is better configured in Kodi itself for all cached images using [advancedsettings.xml](https://kodi.wiki/view/Advancedsettings.xml#imageres).

**Comment by D4anielCB** [comment]
> I'm not real excited about saving that smaller size into the library data by handling this in the scraper.
> 
> This is better configured in Kodi itself for all cached images using [advancedsettings.xml](https://kodi.wiki/view/Advancedsettings.xml#imageres).

I didn't know about it, im sorry about my ignorance, it should work as expected, thanks for replying.
You should close this

**Comment by rmrector** [comment]
Cheers.
